services:
  backend:
    build: ./back-end
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    
  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "80:80"