openapi: 3.0.0
info: 
  title: Food APIs
  version: 1.0.1
  description: API for managing food items
servers:
  - url: http://localhost:4000/api/food
paths:
  /add:
    post:
      summary: Create new food items
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                image:
                  type: string
                  format: binary  # This specifies that `image` is a file
                category:
                  type: string
      responses:
        '200':
          description: Food item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                  description:
                    type: string
                  image:
                    type: string
                  category:
                    type: string