openapi: 3.0.0
info:
  title: Food API
  version: 1.0.0
  description: API for managing food items.
servers:
  - url: http://localhost:4000/api
paths:
  /food:
    get:
      summary: Get all food items
      responses:
        200:
          description: A list of food items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                    description:
                      type: string
    post:
      summary: Create a new food item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
      responses:
        201:
          description: Food item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                  description:
                    type: string
        400:
          description: Bad request (e.g., missing required fields)
        500:
          description: Internal server error
